name: Flask API CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    # - name: Set Environment Variables
    #   env:
    #     MONGO_URI: "mongodb://localhost:27017/wishlist_db"
    #     FLASK_ENV: "testing"
    #     SECRET_KEY: "test-secret-key"
    #   run: echo "Environment variables set."

    - name: Run linting
      run: pipenv run pylint app/app.py

    - name: Format code with Black
      run: pipenv run black app/

    - name: Run tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        FLASK_ENV: "testing"
        SECRET_KEY: "test-secret-key"
      run: pipenv run pytest tests

    # - name: Run tests
    #   env:
    #     MONGO_URI: "mongodb://localhost:27017/wishlist_db"
    #     FLASK_ENV: "testing"
    #     SECRET_KEY: "test-secret-key"
    #   run: pipenv run pytest tests

    - name: Build Docker image
      run: |
        docker build -t arm9129/flask-api ./app

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push arm9129/flask-api
